### ISSUE TITLE
Things to do ASAP

### ISSUE THREAD

**Issue by krushndayshmookh** [dayshmookh/website-sparc#2]
- [x] rename `gallery` to `projects`
- [ ] video links in projects
- [ ] layout of gallery
- [ ] modal for user info in shop
- [ ] Add button for `shop` in homepage
- [ ] Add `associates` in the logo
- [ ] Add dashboard entry to edit the number of projects and design on the homepage

**Comment by SahilKindarle** [comment]
Gallery ka Architecture

**Comment by SahilKindarle** [comment]
spare associates footer k pass wala
